## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

install:
    - pip install --ignore-installed six --user
    - pip install tornado==4.5.3 --user
    - pip install jupyter_contrib_nbextensions --user
    - jupyter contrib nbextension install --user

after_success:
  - julia -e 'cd(Pkg.dir("SpectralClustering")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("SpectralClustering")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("SpectralClustering")); include(joinpath("docs", "make.jl"))'
